import { rangeFor, shipmentIdFromUrl, statusFor } from '../../lib/shipments'
import { useShipments } from '../../hooks/useShipments'

export default function Report() {
  const { shipments, loading } = useShipments()
  const selectedId = shipmentIdFromUrl()
  const shipment = shipments.find((item) => item.id === selectedId) || shipments[0]
  if (loading) return <section><h2 className="text-2xl font-bold">Report</h2><p className="mt-2 text-sm text-muted">Memuat data shipment...</p></section>
  if (!shipment) return <section><h2 className="text-2xl font-bold">Report</h2><p className="mt-2 text-sm text-muted">Shipment belum tersedia.</p></section>
  const range = rangeFor(shipment); const status = statusFor(shipment.temperature, shipment); const temperatureReady = shipment.temperature >= range.min && shipment.temperature <= range.max; const ready = temperatureReady && !['Ditahan', 'Karantina'].includes(shipment.status)
  return <section id="report" className="scroll-mt-24"><div className="mb-5"><h2 className="mt-1 text-2xl font-bold">Pre-shipment compliance report</h2></div><div className="rounded-xl border border-line bg-white p-6 shadow-panel lg:p-8"><div className="flex flex-wrap justify-between gap-5 border-b border-line pb-6"><div><strong className="block text-2xl text-anteraja">anteraja</strong><small className="text-[10px] font-bold tracking-[.25em] text-muted">PHARMA</small></div><div className="text-left sm:text-right"><small className="block text-xs text-muted">Simulation ID</small><strong>{shipment.id}</strong></div></div><div className={`mt-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border p-5 ${ready ? 'border-[#bdebdc] bg-[#effaf6]' : 'border-[#e7b4b0] bg-[#fff6f5]'}`}><div><small className={`block text-xs ${ready ? 'text-success' : 'text-danger'}`}>Final status</small><strong className={`mt-1 block text-xl font-bold ${ready ? 'text-success' : 'text-danger'}`}>{ready ? 'READY FOR SHIPMENT' : 'HOLD FOR REVIEW'}</strong></div><span className={`text-sm font-bold ${ready ? 'text-success' : 'text-danger'}`}>{ready ? `Verified in range ${range.label}` : `Perlu pemeriksaan · ${status.label}`}</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-lg bg-[#f8f9fa] p-4"><small className="text-xs text-muted">Category</small><strong className="mt-1 block">{shipment.category}</strong><small className="text-xs text-muted">{range.label}</small></div><div className="rounded-lg bg-[#f8f9fa] p-4"><small className="text-xs text-muted">Temperature</small><strong className="mt-1 block">{shipment.temperature.toFixed(1)}°C</strong><small className={`text-xs ${status.tone}`}>{status.label}</small></div><div className="rounded-lg bg-[#f8f9fa] p-4"><small className="text-xs text-muted">Rute</small><strong className="mt-1 block">{shipment.origin} → {shipment.destination}</strong><small className="text-xs text-muted">{shipment.weight} kg chargeable</small></div></div><div className="mt-6 flex flex-wrap gap-3"><button id="printReport" type="button" onClick={() => window.print()} className="rounded-lg bg-anteraja px-5 py-3 text-sm font-bold text-white hover:bg-anteraja-dark">Print / save PDF</button></div></div></section>
}